version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Use AWS Corretto 17 for Java 17
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Preparing for the build"
      - mvn --version # Confirm Maven is installed

  build:
    commands:
      - echo "Building the Java application using Maven"
      - mvn clean package # Compile and package the application
      - echo "Build completed"

  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 cp ./target s3://my-application
      - echo "Deployment completed successfully"

artifacts:
  files:
    - target/sample-java-app-1.0.0.jar # Specify the packaged JAR file

